apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-ts
  namespace: edu-oe
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-ts
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames: [edu-oe]
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-py
  namespace: edu-oe
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-py
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames: [edu-oe]
